name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm --prefix test/node_modules/node-fetch-2 ci
      - run: npm run patch-undici
      - run: npm run lint
      - run: npm run type-check
      - run: npm run build
      - run: npm test
